return {
  version = "1.10",
  luaversion = "5.1",
  tiledversion = "1.10.1",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 100,
  height = 100,
  tilewidth = 32,
  tileheight = 32,
  nextlayerid = 20,
  nextobjectid = 1,
  properties = {
    ["Day"] = "true",
    ["Night"] = "false"
  },
  tilesets = {
    {
      name = "grass",
      firstgid = 1,
      class = "",
      tilewidth = 32,
      tileheight = 32,
      spacing = 0,
      margin = 0,
      columns = 3,
      image = "grass.png",
      imagewidth = 96,
      imageheight = 192,
      transparentcolor = "#ffaa00",
      objectalignment = "unspecified",
      tilerendersize = "tile",
      fillmode = "stretch",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 32,
        height = 32
      },
      properties = {},
      wangsets = {},
      tilecount = 18,
      tiles = {}
    },
    {
      name = "grassalt",
      firstgid = 19,
      class = "",
      tilewidth = 32,
      tileheight = 32,
      spacing = 0,
      margin = 0,
      columns = 3,
      image = "grassalt.png",
      imagewidth = 96,
      imageheight = 192,
      transparentcolor = "#ffaa00",
      objectalignment = "unspecified",
      tilerendersize = "tile",
      fillmode = "stretch",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 32,
        height = 32
      },
      properties = {},
      wangsets = {},
      tilecount = 18,
      tiles = {}
    },
    {
      name = "dirt",
      firstgid = 37,
      class = "",
      tilewidth = 32,
      tileheight = 32,
      spacing = 0,
      margin = 0,
      columns = 3,
      image = "dirt.png",
      imagewidth = 96,
      imageheight = 192,
      transparentcolor = "#ffaa00",
      objectalignment = "unspecified",
      tilerendersize = "tile",
      fillmode = "stretch",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 32,
        height = 32
      },
      properties = {},
      wangsets = {},
      tilecount = 18,
      tiles = {}
    },
    {
      name = "dirt2",
      firstgid = 55,
      class = "",
      tilewidth = 32,
      tileheight = 32,
      spacing = 0,
      margin = 0,
      columns = 3,
      image = "dirt2.png",
      imagewidth = 96,
      imageheight = 192,
      transparentcolor = "#ffaa00",
      objectalignment = "unspecified",
      tilerendersize = "tile",
      fillmode = "stretch",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 32,
        height = 32
      },
      properties = {},
      wangsets = {},
      tilecount = 18,
      tiles = {}
    },
    {
      name = "hole",
      firstgid = 73,
      class = "",
      tilewidth = 32,
      tileheight = 32,
      spacing = 0,
      margin = 0,
      columns = 3,
      image = "hole.png",
      imagewidth = 96,
      imageheight = 192,
      transparentcolor = "#ffaa00",
      objectalignment = "unspecified",
      tilerendersize = "tile",
      fillmode = "stretch",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 32,
        height = 32
      },
      properties = {},
      wangsets = {},
      tilecount = 18,
      tiles = {}
    },
    {
      name = "holek",
      firstgid = 91,
      class = "",
      tilewidth = 32,
      tileheight = 32,
      spacing = 0,
      margin = 0,
      columns = 3,
      image = "holek.png",
      imagewidth = 96,
      imageheight = 192,
      transparentcolor = "#ffaa00",
      objectalignment = "unspecified",
      tilerendersize = "tile",
      fillmode = "stretch",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 32,
        height = 32
      },
      properties = {},
      wangsets = {},
      tilecount = 18,
      tiles = {}
    },
    {
      name = "holemid",
      firstgid = 109,
      class = "",
      tilewidth = 32,
      tileheight = 32,
      spacing = 0,
      margin = 0,
      columns = 3,
      image = "holemid.png",
      imagewidth = 96,
      imageheight = 192,
      transparentcolor = "#ffaa00",
      objectalignment = "unspecified",
      tilerendersize = "tile",
      fillmode = "stretch",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 32,
        height = 32
      },
      properties = {},
      wangsets = {},
      tilecount = 18,
      tiles = {}
    },
    {
      name = "house",
      firstgid = 127,
      class = "",
      tilewidth = 32,
      tileheight = 32,
      spacing = 0,
      margin = 0,
      columns = 9,
      image = "house.png",
      imagewidth = 288,
      imageheight = 224,
      transparentcolor = "#ffaa00",
      objectalignment = "unspecified",
      tilerendersize = "tile",
      fillmode = "stretch",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 32,
        height = 32
      },
      properties = {},
      wangsets = {},
      tilecount = 63,
      tiles = {
        {
          id = 0,
          properties = {
            ["obstacle"] = "1"
          }
        },
        {
          id = 1,
          properties = {
            ["obstacle"] = "1"
          }
        },
        {
          id = 2,
          properties = {
            ["obstacle"] = "1"
          }
        },
        {
          id = 9,
          properties = {
            ["obstacle"] = "1"
          }
        },
        {
          id = 10,
          properties = {
            ["obstacle"] = "1"
          }
        },
        {
          id = 11,
          properties = {
            ["obstacle"] = "1"
          }
        },
        {
          id = 18,
          properties = {
            ["obstacle"] = "1"
          }
        },
        {
          id = 19,
          properties = {
            ["obstacle"] = "1"
          }
        },
        {
          id = 20,
          properties = {
            ["obstacle"] = "1"
          }
        }
      }
    },
    {
      name = "bridges",
      firstgid = 190,
      class = "",
      tilewidth = 32,
      tileheight = 32,
      spacing = 0,
      margin = 0,
      columns = 6,
      image = "bridges.png",
      imagewidth = 192,
      imageheight = 224,
      transparentcolor = "#ffaa00",
      objectalignment = "unspecified",
      tilerendersize = "tile",
      fillmode = "stretch",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 32,
        height = 32
      },
      properties = {},
      wangsets = {},
      tilecount = 42,
      tiles = {}
    },
    {
      name = "rock",
      firstgid = 232,
      class = "",
      tilewidth = 32,
      tileheight = 32,
      spacing = 0,
      margin = 0,
      columns = 2,
      image = "rock.png",
      imagewidth = 64,
      imageheight = 32,
      transparentcolor = "#ffaa00",
      objectalignment = "unspecified",
      tilerendersize = "tile",
      fillmode = "stretch",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 32,
        height = 32
      },
      properties = {},
      wangsets = {},
      tilecount = 2,
      tiles = {}
    },
    {
      name = "signs",
      firstgid = 234,
      class = "",
      tilewidth = 32,
      tileheight = 32,
      spacing = 0,
      margin = 0,
      columns = 3,
      image = "signs.png",
      imagewidth = 96,
      imageheight = 64,
      transparentcolor = "#ffaa00",
      objectalignment = "unspecified",
      tilerendersize = "tile",
      fillmode = "stretch",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 32,
        height = 32
      },
      properties = {},
      wangsets = {},
      tilecount = 6,
      tiles = {}
    },
    {
      name = "mountains",
      firstgid = 240,
      class = "",
      tilewidth = 32,
      tileheight = 32,
      spacing = 0,
      margin = 0,
      columns = 12,
      image = "mountains.png",
      imagewidth = 384,
      imageheight = 288,
      transparentcolor = "#ffaa00",
      objectalignment = "unspecified",
      tilerendersize = "tile",
      fillmode = "stretch",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 32,
        height = 32
      },
      properties = {},
      wangsets = {},
      tilecount = 108,
      tiles = {}
    },
    {
      name = "treetop",
      firstgid = 348,
      class = "",
      tilewidth = 32,
      tileheight = 32,
      spacing = 0,
      margin = 0,
      columns = 6,
      image = "treetop.png",
      imagewidth = 192,
      imageheight = 224,
      transparentcolor = "#ffaa00",
      objectalignment = "unspecified",
      tilerendersize = "tile",
      fillmode = "stretch",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 32,
        height = 32
      },
      properties = {},
      wangsets = {},
      tilecount = 42,
      tiles = {}
    },
    {
      name = "trunk",
      firstgid = 390,
      class = "",
      tilewidth = 32,
      tileheight = 32,
      spacing = 0,
      margin = 0,
      columns = 6,
      image = "trunk.png",
      imagewidth = 192,
      imageheight = 96,
      transparentcolor = "#ffaa00",
      objectalignment = "unspecified",
      tilerendersize = "tile",
      fillmode = "stretch",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 32,
        height = 32
      },
      properties = {},
      wangsets = {},
      tilecount = 18,
      tiles = {}
    },
    {
      name = "water",
      firstgid = 408,
      class = "",
      tilewidth = 32,
      tileheight = 32,
      spacing = 0,
      margin = 0,
      columns = 3,
      image = "water.png",
      imagewidth = 96,
      imageheight = 192,
      transparentcolor = "#ffaa00",
      objectalignment = "unspecified",
      tilerendersize = "tile",
      fillmode = "stretch",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 32,
        height = 32
      },
      properties = {},
      wangsets = {},
      tilecount = 18,
      tiles = {}
    },
    {
      name = "waterfall",
      firstgid = 426,
      class = "",
      tilewidth = 32,
      tileheight = 32,
      spacing = 0,
      margin = 0,
      columns = 3,
      image = "waterfall.png",
      imagewidth = 96,
      imageheight = 160,
      transparentcolor = "#ffaa00",
      objectalignment = "unspecified",
      tilerendersize = "tile",
      fillmode = "stretch",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 32,
        height = 32
      },
      properties = {},
      wangsets = {},
      tilecount = 15,
      tiles = {}
    },
    {
      name = "watergrass",
      firstgid = 441,
      class = "",
      tilewidth = 32,
      tileheight = 32,
      spacing = 0,
      margin = 0,
      columns = 3,
      image = "watergrass.png",
      imagewidth = 96,
      imageheight = 192,
      transparentcolor = "#ffaa00",
      objectalignment = "unspecified",
      tilerendersize = "tile",
      fillmode = "stretch",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 32,
        height = 32
      },
      properties = {},
      wangsets = {},
      tilecount = 18,
      tiles = {}
    },
    {
      name = "barrel",
      firstgid = 459,
      class = "",
      tilewidth = 32,
      tileheight = 32,
      spacing = 0,
      margin = 0,
      columns = 4,
      image = "barrel.png",
      imagewidth = 128,
      imageheight = 64,
      transparentcolor = "#ffaa00",
      objectalignment = "unspecified",
      tilerendersize = "tile",
      fillmode = "stretch",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 32,
        height = 32
      },
      properties = {},
      wangsets = {},
      tilecount = 8,
      tiles = {}
    },
    {
      name = "buckets",
      firstgid = 467,
      class = "",
      tilewidth = 32,
      tileheight = 32,
      spacing = 0,
      margin = 0,
      columns = 3,
      image = "buckets.png",
      imagewidth = 96,
      imageheight = 64,
      transparentcolor = "#ffaa00",
      objectalignment = "unspecified",
      tilerendersize = "tile",
      fillmode = "stretch",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 32,
        height = 32
      },
      properties = {},
      wangsets = {},
      tilecount = 6,
      tiles = {}
    },
    {
      name = "shadow",
      firstgid = 473,
      class = "",
      tilewidth = 32,
      tileheight = 32,
      spacing = 0,
      margin = 0,
      columns = 5,
      image = "shadow.png",
      imagewidth = 160,
      imageheight = 64,
      transparentcolor = "#ffaa00",
      objectalignment = "unspecified",
      tilerendersize = "tile",
      fillmode = "stretch",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 32,
        height = 32
      },
      properties = {},
      wangsets = {},
      tilecount = 10,
      tiles = {}
    }
  },
  layers = {
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 100,
      height = 100,
      id = 1,
      name = "Ground",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJzt0UEKg0AMQNHse//7ditl1FBrE8wLvJUzGOZHmE7zukHFPznu8c037uux9+561PT4bBOLb/y/ix49bBtsO+gB8AzZqd5ziuzsna/ef5qzHpkmmTPkW6zeP9sCnmo11TtNd6VDXLw/UXaO7uuhB/m21XsAAHQRDXZAS/iFaLADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATPQGxiqkug=="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 100,
      height = 100,
      id = 2,
      name = "Dirt",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJzt2M0KgkAUgFHfyE22b1Pv/0ZtGhgug/hT3rgc4UAixXg/THGepmkGgARLkL2eCvo53k80yT6PKpZPh2atF9c1GX2+HfwNzndo+0f+szQBfumxQfxO27LXXlE/96ce6eLsXys9Rlv2+qvZ2yN2yV5/NaP5uz7yxGuj79PuJ32PUZvsc6jkyPNV7KFJvr6DJnkNRj3iMb5nz7tDrp2/Nv9FDwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAoKI3GagrSA=="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 100,
      height = 100,
      id = 3,
      name = "Hole Mountain",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJzt0buOQQEUhlGiNnr6mYpQukxpLpU77/8QaP2RUzoacU7CWslX7WZn70aDV3dMp5LONe71rprN8lnrzoznaOfmwzS6cXv/qN40N5+l79RPg/RR1PGPyv3m5n/pP43TJHWLev5RuU1uvk27NE8/6bPoyz8AAACgUou0TKu6F+FqnTZpW/ciXO3SPh3qXgQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHnQBZq0P/Q=="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 100,
      height = 100,
      id = 4,
      name = "Grass",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJzt22tuEzEQAGBDgT4o9PEPWmi5GUfjKBytdsGKs/VuEuLdtej3SaNKaVJFmczYnu2ehhDOYpwHenAR42OMy7XfCM8+xfgc42rtNwLAf+NNCL/+/vy97jt5vXz264s5+Fl57IV3Df4ubeyTi1oOAVo5Ddvzq9SXvsT4GuOu8ryxMP9qoza/uo/xLcb3yvPGIr8+ryGHrv38UZtfjeXjOsZtmM4HbZR7o131UeblJmzyYX81j4cYjzF+FI/lfNwWUdbH+2AtWVLuaylOwnYursMmV6le9K75lfuwVCu5Tw1zYi2ZX9or5X6V+tKHsJ2Dm/ByLeE45fmi1v/LfrUrXGs8Xvr+vw2bz9NeaT2pNlIPKvdI9knrSb0o7Zlyffxr33HtpJ2Uk9Z9X8+bx9QsUU9b3tQs0d52eVP5SHsANbKsvN5P5UT/Wtau6x/613xq63eekcjH8vatBb1rGWP5yOfF4dlxbG1RK23k2eHwc74sfl+eHcfyZ+/VTp5p7fN9H9t/pRoy621j+J3f9dnWakR9tHFIbWRj13OtIcerXXs6pO+Ur9ev2hj+3yLrct9tX9x3CwDQnjNIX5xB+uIMAgDQjrNHX5w9+uLsAQAAAOsyu+qL2VVfzK4AAAAAAAAAAAAAgNfEPQZ9cY9BX9xj0Icn6i8UNw=="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 100,
      height = 100,
      id = 5,
      name = "water",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJzt1sEJgEAMRcFN/x0IoiJap9qAue0Gdgb+PfAuaQ0AAAAYbYt8e4y+ch5X/G95d+pRxqFHKXrUokctetSiR1/Zr7vq0VX273679QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABgcg+LLx/O"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 100,
      height = 100,
      id = 6,
      name = "Shadows",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJzt0bEJACAQBEHtv0LBQDsxMbAD72GmgoVtDQAAoIbRfxfwmn5E8SOLH1n8yLDuh+0HAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABRwbpQYS"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 100,
      height = 100,
      id = 7,
      name = "Buildings",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJztzrENgDAMAEFvDnRAF7JwjOQBkCjc3EnffwQAAAAAf2zZXh2tJ7zO7Kru5hciRvZUs/kFAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAvloGggZt"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 100,
      height = 100,
      id = 8,
      name = "Under Bridge",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJzt06ERACAQA8F8/+UxQw90gcW/4MWuOhmTBAAAAACg7zy9Ktn1bQqM5hsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADDfBTeXA2w="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 100,
      height = 100,
      id = 9,
      name = "Misc Objects Bottoms",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJzt2DEKg0AQBVBzHA/gATxbWg8XU1iZdILeIgZSSAiYRmZx3oNptvow7M7uVhUAlK2+RCdgq9GPorT6AQCw6/bHnWk+PkYK41qPTT0/69ewRLlNP+qtC0uU2/c5M3jPAXCAfp0vdzOmWEt0AABIyL/feegl2dkDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEOMFnBgTOg=="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 100,
      height = 100,
      id = 10,
      name = "BuildingDoors",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJztzrENAAAEADC3Wz1tNpok0l7QCAAAAAD4Ja8DDHUdAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgKUGEFwBDg=="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 100,
      height = 100,
      id = 11,
      name = "TreeTrunk Bottom",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJzt0UEKgDAMRcHm8uJCXdQeuIHgGSplBj7ZBl5rAAAAAAAAfI6oe8baPyhXdrhzjx6/0LPDmxt6AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALC5CRrPBHc="
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 12,
      name = "Enemy",
      class = "",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 13,
      name = "Object1",
      class = "",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {}
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 100,
      height = 100,
      id = 14,
      name = "Bridge Above",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJztzrENADAIwDD+v7FwCx35ALWypeyJAAAAAADgN+eWo9rdAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAeEoDJygEUg=="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 100,
      height = 100,
      id = 15,
      name = "Misc Objects Tops",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJzt1sENACAIADHYfzVlJh2CYGLaCe55EQAAAAB0Wvm6AAAAZuz7vuV/AQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPjQAQ03Ams="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 100,
      height = 100,
      id = 16,
      name = "TreeTrunkTop",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJztzjEBAAAIA6CZ3tq+NtgDCUgAAAAAAAD4dtoDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACaDjhZAIk="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 100,
      height = 100,
      id = 17,
      name = "TreeTops",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJzt0bENgDAUQ8GfPYECUpDsPwBmCpByJ7m39KoAAAAAAFjN1qr27GhfP+F1psOVdT1+4U6HkU09AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACW9QCJbQOF"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 100,
      height = 100,
      id = 18,
      name = "Roofs",
      class = "",
      visible = true,
      opacity = 0.87,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJztzrEJgFAQBcHrvwQxE8Xgq9ihL7CHE5mBzbcKAADgm6a0pT3NzS9ULelKd1qbX6ga6Xg7m18AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4G8eo1YH4Q=="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 100,
      height = 100,
      id = 19,
      name = "Roof Objects",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJztzjEBAAAEADDlvTJ7SeCwJVgEAAAw5XWApa4DAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC806iJARQ="
    }
  }
}
