--this file holds all the game constants

--Damage types
RPG_DMG_FIRE 		= 1
RPG_DMG_COLD		= 2
RPG_DMG_POISON		= 3
RPG_DMG_DISEASE		= 4
RPG_DMG_ACID		= 5
RPG_DMG_ELECTRICAL	= 6
RPG_DMG_MAGICAL		= 7
RPG_DMG_SLASHING	= 8
RPG_DMG_IMPACT		= 9
RPG_DMG_PIERCING	= 10
RPG_DMG_CLEAVE		= 11
RPG_DMG_PUMMEL		= 12
RPG_DMG_CLAWS		= 13
RPG_DMG_CRITICAL	= 14
RPG_DMG_PHYSICAL	= 15
RPG_DMG_DRAIN		= 16
RPG_DMG_UNSTOPPABLE	= 17

--RESISTS
RPG_RESIST_PHYSICAL		= 1
RPG_RESIST_MAGICAL		= 2
RPG_RESIST_FIRE			= 3
RPG_RESIST_COLD			= 4
RPG_RESIST_POISON		= 5
RPG_RESIST_DISEASE		= 6
RPG_RESIST_ACID			= 7
RPG_RESIST_ELECTRICAL	= 8
RPG_RESIST_UNSTOPPABLE	= 9

--Drop rate CONST
RPG_FREQ_ALWAYS		= 1
RPG_FREQ_COMMON		= 2
RPG_FREQ_UNCOMMON	= 3
RPG_FREQ_RARE		= 4
RPG_FREQ_VERYRARE	= 5
RPG_FREQ_IMPOSSIBLE	= 6

--QUALITY CONST
RPG_QUALITY_BROKEN		= 1
RPG_QUALITY_WORN		= 2
RPG_QUALITY_NORMAL		= 3
RPG_QUALITY_FINE		= 4
RPG_QUALITY_PRISTINE	= 5

--SPELL TYPES
RPG_SPELL_NOSPECIAL		= 1
RPG_SPELL_HEALING		= 2
RPG_SPELL_HARMFUL		= 3 
RPG_SPELL_AICAST		= 4 
RPG_SPELL_PERSISTENT	= 5 
RPG_SPELL_NOAGGRO		= 6 

--ITEM TYPES
RPG_ITEM_SOULBOUND		= 1
RPG_ITEM_UNIQUE			= 2
RPG_ITEM_ETHEREAL		= 3
RPG_ITEM_INDESTRUCTIBLE	= 4
RPG_ITEM_ARTIFACT		= 5
RPG_ITEM_ENCHANTED		= 6
RPG_ITEM_PREMIUM		= 7
RPG_ITEM_WORLDUNIQUE	= 8
RPG_ITEM_LITERATURE		= 9

--ITEM TRIGGERS
RPG_ITEM_TRIGGER_WORN		= 1
RPG_ITEM_TRIGGER_MELEE		= 2
RPG_ITEM_TRIGGER_DAMAGED	= 3
RPG_ITEM_TRIGGER_USE		= 4
RPG_ITEM_TRIGGER_POISON		= 5

--ITEM PROC TYPES
RPG_ITEMPROC_POISON			= 1
RPG_ITEMPROC_ENCHANTMENT	= 2



--EFFECT TYPES
RPG_EFFECT_WATERBREATHING 	= 1
RPG_EFFECT_LEVITATE			= 2
RPG_EFFECT_PARALYSIS		= 3
RPG_EFFECT_ROOT				= 4
RPG_EFFECT_RESURRECTION		= 5
RPG_EFFECT_STUN				= 6
RPG_EFFECT_SLEEP			= 7
RPG_EFFECT_CHARM			= 8
RPG_EFFECT_INTERRUPT		= 9
RPG_EFFECT_BANISH			= 10
RPG_EFFECT_SUMMONMONSTER	= 11
RPG_EFFECT_SUMMONALLY		= 12

--CHAR SLOTS
RPG_SLOT_HEAD		= 1
RPG_SLOT_LEAR		= 2
RPG_SLOT_REAR		= 3
RPG_SLOT_NECK		= 4
RPG_SLOT_SHOULDERS	= 5
RPG_SLOT_BACK		= 6
RPG_SLOT_CHEST		= 7
RPG_SLOT_ARMS		= 8
RPG_SLOT_HANDS		= 9
RPG_SLOT_LFINGER	= 10
RPG_SLOT_RFINGER	= 11
RPG_SLOT_PRIMARY	= 12
RPG_SLOT_SECONDARY	= 13
RPG_SLOT_RANGED		= 14
RPG_SLOT_AMMO		= 15
RPG_SLOT_WAIST		= 16
RPG_SLOT_LEGS		= 17
RPG_SLOT_FEET		= 18
RPG_SLOT_LWRIST		= 19
RPG_SLOT_RWRIST		= 20
RPG_SLOT_SHIELD		= 21
RPG_SLOT_LIGHT		= 22

--INVENTORY SLOTS
RPG_SLOT_CARRY1		= 23
RPG_SLOT_CARRY2		= 24
RPG_SLOT_CARRY3		= 25
RPG_SLOT_CARRY4		= 26
RPG_SLOT_CARRY5		= 27
RPG_SLOT_CARRY6 	= 28
RPG_SLOT_CARRY7		= 29
RPG_SLOT_CARRY8		= 30
RPG_SLOT_CARRY9		= 31
RPG_SLOT_CARRY10	= 32
RPG_SLOT_CARRY11	= 33
RPG_SLOT_CARRY12	= 34
RPG_SLOT_CARRY13	= 35
RPG_SLOT_CARRY14	= 36
RPG_SLOT_CARRY15	= 37
RPG_SLOT_CARRY16	= 38
RPG_SLOT_CARRY17	= 39
RPG_SLOT_CARRY18	= 40
RPG_SLOT_CARRY19	= 41
RPG_SLOT_CARRY20	= 42
RPG_SLOT_CARRY21	= 43
RPG_SLOT_CARRY22	= 44
RPG_SLOT_CARRY23	= 45
RPG_SLOT_CARRY24	= 46
RPG_SLOT_CARRY25	= 47
RPG_SLOT_CARRY26	= 48
RPG_SLOT_CARRY27	= 49
RPG_SLOT_CARRY28	= 50
RPG_SLOT_CARRY29	= 51
RPG_SLOT_CARRY30	= 52
RPG_SLOT_CARRY31	= 53
RPG_SLOT_CARRY32	= 54
RPG_SLOT_CARRY33	= 55
RPG_SLOT_CARRY34	= 56
RPG_SLOT_CARRY35	= 57


RPG_SLOT_BANK1		= 58
RPG_SLOT_BANK2		= 59
RPG_SLOT_BANK3		= 60
RPG_SLOT_BANK4		= 61
RPG_SLOT_BANK5		= 62
RPG_SLOT_BANK6		= 63
RPG_SLOT_BANK7		= 64
RPG_SLOT_BANK8		= 65
RPG_SLOT_BANK9		= 66
RPG_SLOT_BANK10		= 67
RPG_SLOT_BANK11		= 68
RPG_SLOT_BANK12		= 69
RPG_SLOT_BANK13		= 70
RPG_SLOT_BANK14		= 71
RPG_SLOT_BANK15		= 72
RPG_SLOT_BANK16		= 73
RPG_SLOT_BANK17		= 74
RPG_SLOT_BANK18		= 75
RPG_SLOT_BANK19		= 76
RPG_SLOT_BANK20		= 77
RPG_SLOT_BANK21		= 78
RPG_SLOT_BANK22		= 79
RPG_SLOT_BANK23		= 80
RPG_SLOT_BANK24		= 81
RPG_SLOT_BANK25		= 82
RPG_SLOT_BANK26		= 83
RPG_SLOT_BANK27		= 84
RPG_SLOT_BANK28		= 85
RPG_SLOT_BANK29		= 86
RPG_SLOT_BANK30		= 87
RPG_SLOT_BANK31		= 88
RPG_SLOT_BANK32		= 89
RPG_SLOT_BANK33		= 90
RPG_SLOT_BANK34		= 91
RPG_SLOT_BANK35		= 92

--LOOT SLOTS
RPG_SLOT_LOOT1	= 93
RPG_SLOT_LOOT2	= 94
RPG_SLOT_LOOT3	= 95
RPG_SLOT_LOOT4	= 96
RPG_SLOT_LOOT5	= 97
RPG_SLOT_LOOT6	= 98
RPG_SLOT_LOOT7	= 99
RPG_SLOT_LOOT8	= 100
RPG_SLOT_LOOT9	= 101
RPG_SLOT_LOOT10	= 102
RPG_SLOT_CURSOR	= 103

--SPAWN MODE
RPG_SPAWN_NOASSIST			= 1
RPG_SPAWN_UNIQUE			= 2
RPG_SPAWN_NOCORPSE			= 3
RPG_SPAWN_BANKER			= 4
RPG_SPAWN_INN				= 5
RPG_SPAWN_NOXP				= 6
RPG_SPAWN_MONSTERADVANCED	= 7

--FACTION RATING
RPG_FACTION_HATED		= -250
RPG_FACTION_DISLIKED	= -50
RPG_FACTION_UNDECIDED	= 0
RPG_FACTION_LIKED		= 100
RPG_FACTION_ADORED		= 500


--Material Constants
MATERIALS = [	"Oak","Pine","Ironwood"
				"Copper","Silver","Gold","Iron","Steel","Mithril",
				"Bone","Crystal","Stone"
				"Alexandrite","Aquamarine","Diamond","Emerald","Opal","Pearl","Ruby","Sapphire","Spinel","Topaz",
			]



--Item Constants
ITEM_RING_ALLOWED_RARITIES 	= []
ITEM_RING_ALLOWED_QUALITIES	= []
ITEM_RING_MAX_MATERIALS		= 3
ITEM_RING_ALLOWED_MATERIALS = []
ITEM_RING_ALLOWED_EFFECTS	= []